version: 2

project_name: tally

before:
  hooks:
    - go mod tidy

builds:
  - id: tally
    main: ./cmd/tally
    binary: tally
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/thinktide/tally/internal/cli.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: thinktide
    name: tally
  draft: false
  prerelease: auto

brews:
  - name: tally
    repository:
      owner: thinktide
      name: homebrew-tally
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/thinktide/tally"
    description: "CLI time tracking utility"
    license: "MIT"
    install: |
      bin.install "tally"
    test: |
      system "#{bin}/tally", "version"
